package emergencyRoom;

import java.io.Serializable;
import java.util.TreeMap;

public class VitalSigns implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -7304712462710950531L;
	/** The collection of times mapped with vital signs. */
	private TreeMap<Long, String[]> vitals;
	/** The Vital Signs heart rate, systolic, diastolic, temperature. */
	private String diastolic, systolic, hr, temp;
	
	/**
	 * Initializes the vital sign values.
	 */	
	public VitalSigns(){
		this.vitals = new TreeMap<Long, String[]>();
		this.diastolic = "None";
		this.hr = "None";
		this.temp = "None";
		this.systolic = "None";
	}

	/**
	 * Updates the value of the vital signs of a patient. These values would be stored into
	 * an array which would then be stored as the value of a TreeMap with the corresponding
	 * update time as the key.
	 * 
	 * @param time Current time generated by the Android device.
	 * @param bloodPressure The blood pressure of a patient.
	 * @param heartRate The heart rate of a patient.
	 * @param temperature The temperature of a patient.
	 */	
	public void update(long time, String systolicBP, String diastolicBP, String heartRate, String temperature){
		//If user enters nothing, null will be transfered from activity to this method
		if (systolicBP != null){
			setSystolic(systolicBP);
		}
		if (diastolicBP != null){
			setDiastolic(diastolicBP);
		}
		if (heartRate != null){
			setHr(heartRate);
		} 
		if (temperature != null){
			setTemp(temperature);
		}
		String[] anArray;
		anArray = new String[4];
		//Gets old or new values if user left field(s) blank
		anArray[0] = getHr();
		anArray[1] = getSystolic();
		anArray[2] = getDiastolic();
		anArray[3] = getTemp();
		this.vitals.put(time, anArray);
		
	}

	/**
	 * Returns the diastolic blood pressure.
	 * @return The Diastolic blood pressure of a Patient at a time.
	 */
	public String getDiastolic() {
		return diastolic;
	}

	/**
	 * Sets the diastolic blood pressure.
	 * @param diastolic The new diastolic blood pressure of a Patient at a time.
	 */
	public void setDiastolic(String diastolic) {
		if (diastolic instanceof String){
			this.diastolic = diastolic;
		}
	}

	/**
	 * Returns the systolic blood pressure.
	 * @return The Systolic blood pressure of a Patient at a time.
	 */
	public String getSystolic() {
		return systolic;
	}

	/**
	 * Sets the systolic blood pressure.
	 * @param The new systolic blood pressure of a Patient at a time.
	 */
	public void setSystolic(String systolic) {
		if (systolic instanceof String){
			this.systolic = systolic;
		}
	}

	/**
	 * Display the vital signs of a Patient.
	 * @return The vital signs of a Patient associated with time.
	 */
	public String toString() {
		//Used to test that data is correctly displayed in map
		String adj = "";
		for(Long key: vitals.keySet()){
			adj += "," + Long.toString(key) + "=" + vitals.get(key)[0] + "&" + vitals.get(key)[1] +"&" + vitals.get(key)[2] + "&" + vitals.get(key)[3];
		}
		
		return adj;
		
	}

	/**
	 * Returns the TreeMap object.
	 * @return The vital signs of a Patient as a TreeMap.
	 */
	public TreeMap<Long, String[]> getVitals() {
		return vitals;
	}

	/**
	 * Sets the TreeMap object to a given value.
	 * @param vitals The new TreeMap of all vital signs of a Patient.
	 */
	public void setVitals(TreeMap<Long, String[]> vitals) {
		this.vitals = vitals;
	}

	/**
	 * Returns the heart rate of a Patient.
	 * @return The current heart rate of a Patient.
	 */
	public String getHr() {
		return hr;
	}

	/**
	 * Sets the heart rate of a Patient.
	 * @param hr The new heart rate value for a Patient.
	 */
	public void setHr(String hr) {
		if (hr instanceof String){
			this.hr = hr;
		}
	}

	/**
	 * Returns the temperature of a patient.
	 * @return The current temperature of a Patient.
	 */
	public String getTemp() {
		return temp;
	}

	/**
	 * Sets the temperature of a Patient.
	 * @param temp The new temperature value for a Patient.
	 */
	public void setTemp(String temp) {
		if (temp instanceof String){
			this.temp = temp;
		}
	}
}
